### PR TITLE
about: Update the about app with a few changes

### PR DESCRIPTION
**Pull request by pixl-8**
Changes are:
1. Replaced © symbol (it was coming up as ?) with (c)
2. Hardcoded version value (it was not showing, it just had an error and debug code)
3. Changed the "Ok" button to display "Close"
⚠When updating the OS to a new version you will have to update the string!⚠

### CODE REVIEW

**Comment by caelwithcats** [comment]
there are a few problems with this PR
- Why did you remove the ©
- Why did hard code the version
- skiftOS is written skiftOS not SkiftOS
- also this won't work without modification to the source file

**Comment by pixl-8** [comment]
I removed the © because it was coming up as ?
I hardcoded the version because it produces an error where the version is meant to go

**Comment by pixl-8** [comment]
What do mean modification to the source file @caelwithcats?

**Comment by caelwithcats** [comment]
in https://github.com/skiftOS/skift/blob/master/applications/about/main.cpp

**Comment by caelwithcats** [comment]
before you make a pull request please test it

**Comment by pixl-8** [comment]
@caelwithcats, how about now?

**Comment by caelwithcats** [comment]
```
Was it because the function for the version label pointed to nothing?
```
that block of code overwrites the text on label

**Comment by pixl-8** [comment]
Oh ok 👍

**Comment by NicolasVanBossuyt** [comment]
I think a better way to update the version number is to use a compile-time define like other __BUILD_XXX__ variables. Also for the (C) symbol, the correct fix is to regen the fonts using toolbox/font-generator.html or finish the TrueType font renderer in libgraphic.

**Pull request closed without merging**
