### PR TITLE
Fixed sentence (I guess?) and changed position of notice

### PR DESCRIPTION
**Pull request by busybox11**

### CODE REVIEW

**Comment by NicolasVanBossuyt** [comment]
Here is my try for improving the phrasing:
> We've moved the project to C++ recently. So don't expect it to be idiomatic C++ yet. There is still a lot of work to be done. And your help is welcome :)

**Comment by busybox11** [comment]
Thanks!
I edited it a bit to make it more "consistent", I guess?

**Comment by NicolasVanBossuyt** [comment]
I like it :)

**Comment by busybox11** [comment]
Thanks!

**Pull request merged**
