### PR TITLE
Adding packages support for openSUSE and fixing some Fedora packages errors

### PR DESCRIPTION
**Pull request by todoroki-san**
build-guide: Adding packages support for openSUSE and fixing some Fedora packages errors

### CODE REVIEW

**Comment by todoroki-san** [comment]
Pull request #333 😳

**Comment by sleepy-monax** [comment]
Please conform to the project commit style

**Comment by sleepy-monax** [comment]
https://github.com/skiftOS/skift/blob/main/manual/meta/contributing.md#getting-your-pull-request-merged

**Comment by todoroki-san** [comment]
> https://github.com/skiftOS/skift/blob/main/manual/meta/contributing.md#getting-your-pull-request-merged

Better?

**Comment by sleepy-monax** [comment]
No you didn't change the name of the commit:

It should be:

```
build-guide: Adding packages support for openSUSE and fixing some Fedora packages errors.
```

**Comment by todoroki-san** [comment]
OK, i have to change the comment right?

**Comment by feliwir** [comment]
No, you need to change the message of your last commit. You probably need `git commit --amend` followed by `git push --force` to change it on your remote.

**Comment by todoroki-san** [comment]
Oh well, this pull request isn't that important after all, and sorry for the mess I made

**Pull request closed without merging**
