### PR TITLE
[NEW] Add --list option to man

### PR DESCRIPTION
**Pull request by caelwithcats**
Also fixes a lot of bugs

### CODE REVIEW

**Comment by NicolasVanBossuyt** [comment]
I think you forgot to include String.h in Path.h

**Comment by caelwithcats** [comment]
@NicolasVanBossuyt yeah, oops. Fixing it now

**Comment by caelwithcats** [comment]
now it's fixed

**Comment by NicolasVanBossuyt** [comment]
Nice, let's merge this :)

**Pull request merged**
