### PR TITLE
Grub: add all_video module

### PR DESCRIPTION
**Pull request by atomicbitty**
Add `all_video` module to GRUB so that it works with UEFI systems.

### CODE REVIEW

**Comment by NicolasVanBossuyt** [comment]
Neet, now I can boot skift on my system without legacy mode :)

**Comment by atomicbitty** [comment]
Yeah, this annoyed me a lot when I was testing my OS on real hardware.

**Comment by NicolasVanBossuyt** [comment]
Did it run well on your hardware?

**Comment by atomicbitty** [comment]
sorry, are you asking about skift or my OS?

**Comment by atomicbitty** [comment]
Yeah, it ran pretty normally, just some problems with performance in the graphics part... but overall pretty normal.

**Comment by NicolasVanBossuyt** [comment]
Yes, I don't know why but the framebuffer we got from grub is slow to copy pixel to :/

**Comment by atomicbitty** [comment]
could you point in which file the back buffer is copied to the front buffer? and the file in which invalidated (dirty) rects are draw? I would like to try to help.

**Comment by NicolasVanBossuyt** [comment]
The invalidation of rectangle and compositing is done here https://github.com/skiftOS/skift/blob/master/applications/compositor/Renderer.cpp
and the copy to the framebuffer here:
https://github.com/skiftOS/skift/blob/master/kernel/graphics/Framebuffer.cpp

**Pull request merged**
