### PR TITLE
Libsystem: optimize memcpy.

### PR DESCRIPTION
**Pull request by atomicbitty**
I wrote an optimized version of the `memcpy` because it is a very essential function that may make a difference in the performance of the OS. Then I made some tests on user space that showed that the function was 1-5x faster than the current one, so it is quite a good improvement I guess. 
Hope it's useful and if you see something wrong or not conforming the style, please tell me so that I can fix it.

### CODE REVIEW

**Comment by NicolasVanBossuyt** [comment]
Nice patch and nice speedup :) I think you can get even more speed by using the movq instruction ;)

**Comment by atomicbitty** [comment]
Hey, unfortunately the `movq` instruction is only available in 64-bit long mode, I could have used MMX, but I think some extra trickery is necessary to enable it on your OS. 

Here are the results on my 1.5GHz laptop:

```
0*1000000 bytes:         1287    1690
32*1000000 bytes:       3330    6019
64*1000000 bytes:       4462    8698
96*1000000 bytes:       3927   12189
128*1000000 bytes:     4448   16614
160*1000000 bytes:     5012   22370
192*1000000 bytes:     5580   26441
224*1000000 bytes:     6087   30367
256*1000000 bytes:     6603   34208
288*1000000 bytes:     7182   38258
320*1000000 bytes:     6662   42189
352*1000000 bytes:     7156   45949
384*1000000 bytes:     6821   49630
416*1000000 bytes:     7360   53746
448*1000000 bytes:     7022   57717
480*1000000 bytes:     7555   61770
512*1000000 bytes:     7331   65903
544*1000000 bytes:     7882   69906
576*1000000 bytes:     7715   73724
608*1000000 bytes:     8039   77079
640*1000000 bytes:     7740   81037
672*1000000 bytes:     8292   84851
704*1000000 bytes:     7972   89019
736*1000000 bytes:     8622   92549
768*1000000 bytes:     8253   96495
800*1000000 bytes:     8817  100359
832*1000000 bytes:     8726  104427
864*1000000 bytes:     9327  108380
896*1000000 bytes:    10167  112030
928*1000000 bytes:    10743  116028
960*1000000 bytes:    10524  119771
992*1000000 bytes:    11068  123924
```
And here is the [code of the benchmark](https://gofile.io/d/ci0Fb0), because the laptop I'm using now is kinda old and clunky, so the results may differ in yours. just run `./compile.sh` and `./benchmark`.

**Comment by NicolasVanBossuyt** [comment]
The system support mmx and sse :)

**Comment by atomicbitty** [comment]
Oh, I didn't know, maybe I can write the SSE version later. :-)

**Comment by NicolasVanBossuyt** [comment]
Hi, with the switch from C to C++ I can no longer merge your branch with master. Can you resolve the conflicts?

**Pull request closed without merging**
