### PR TITLE
use a bettew wanguage 

### PR DESCRIPTION
**Pull request by Supercip971**
OwO

### CODE REVIEW

**Comment by sleepy-monax** [comment]
Only the readme... I'm disappointed of you

**Comment by Supercip971** [comment]
but the twanswation take time

**Comment by sleepy-monax** [comment]
Pain is temporary, Glory is forever ♾️

**Comment by Supercip971** [comment]
> forever
ok i'm twanswating othew things wight now

**Comment by Supercip971** [comment]
now we have convewted buiwding.md code_of_conduct.md and coding_stywe.md

**Comment by Supercip971** [comment]
this is a bettew headew
image

**Comment by Supercip971** [comment]
sorry the joke is over

**Pull request closed without merging**
