### PR TITLE
Wc command added

### PR DESCRIPTION
**Pull request by pvatshal**
I have implemented the wc command with three switches. Switches:- -l for number of lines, -w for number of words, -m for number of characters.
Screenshot 2020-11-04 at 3 28 02 PM

### CODE REVIEW

**Comment by Keyboard-Slayer** [comment]
Read message on #202

**Review by Keyboard-Slayer — CHANGES_REQUESTED** [review]
Comments on  #202

**Comment by pvatshal** [comment]
I didn't understood the 4th problem.

**Comment by Keyboard-Slayer** [comment]
On your GNU+Linux check the output of the command and make it looks like it

**Pull request closed without merging**
