### PR TITLE
Fix Broken Manual Link in readme.md

### PR DESCRIPTION
**Pull request by WebSnke**

### CODE REVIEW

**Comment by keyboard-slayer** [comment]
I don't think that we want to link the old manual for the newer skift

(ping @sleepy-monax)

**Comment by sleepy-monax** [comment]
Yeah definitely, new-skift a completely different animal than old-skift. Thanks for the contribution but this might confuse some people if the doc link to an unrelated project

**Comment by WebSnke** [comment]
> Yeah definitely, new-skift a completely different animal than old-skift. Thanks for the contribution but this might confuse some people if the doc link to an unrelated project

Ok, so should we remove the broken link to the manual until the new one is ready?

**Comment by sleepy-monax** [comment]
Yes this is the right thing to do :)

**Comment by WebSnke** [comment]
> Yes this is the right thing to do :)

@sleepy-monax 
Done.

**Comment by keyboard-slayer** [comment]
LGTM :+1:

next time, you can remove your last commit with

```
git commit --reset HEAD~1
```

and do you modification, make a commit like normal, then do a 
```
git push --force
```

But don't worry we can squash them into one commit :grin: 

Also for next time, check out the commit message [guideline](https://www.conventionalcommits.org/en/v1.0.0/) :wink:

**Comment by WebSnke** [comment]
> Also for next time, check out the commit message [guideline](https://www.conventionalcommits.org/en/v1.0.0/) 😉

Thanks, I didn't knew these exist!

**Comment by keyboard-slayer** [comment]
Np :stuck_out_tongue:

**Comment by WebSnke** [comment]
@sleepy-monax 
So is it ready to be merged?

**Pull request merged**
