### PR TITLE
Changed File Explorer name to File Manager

### PR DESCRIPTION
**Pull request by pixl-8**
Changed the File Explorer name to File Manager

### CODE REVIEW

**Comment by NicolasVanBossuyt** [comment]
Hi, I can't merge this change because it breaks the build. Also, can you please take a look at CONTRIBUTING.md and pay special attention to the section about commit naming.

**Comment by pixl-8** [comment]
I'm confused about how it breaks the build. Could you please explain (I'm a bit new to GitHub)

**Comment by NicolasVanBossuyt** [comment]
Ok, so here is where you got it wrong ;)

```make
APPS += FILE_EXPLORER

FILE_EXPLORER_NAME = file-manager
FILE_EXPLORER_LIBS = widget graphic json
FILE_EXPLORER_ICONS = \
	folder
```

Looks like you tried to change to name of the application by editing the .build.mk, but in order for this to work you need to change all the references to "file-explorer" here and change the directory name.


```make
APPS += FILE_MANAGER

FILE_MANAGER_NAME = file-manager
FILE_MANAGER_LIBS = widget graphic json
FILE_MANAGER_ICONS = \
	folder
```

Please avoid using the GitHub built-in editor and use a GIT client instead. Because the GitHub editor prevents you from editing multiple files and testing your changes.

I will close #122 and #123 because these two need to be one PR.

**Comment by pixl-8** [comment]
Ok 👍

**Pull request closed without merging**
