### PR TITLE
Add a snow wallpaper

### PR DESCRIPTION
**Pull request by caelwithcats**
I was taking some picture of the snow (yes, it was snowing in Australia, this is unusual) and thought this one was the best.

Uncroped image: https://i.imgur.com/0azwZxk.jpg

### CODE REVIEW

**Comment by busybox11** [comment]
Don't wanna be rude but this picture is... Not great, IMO.
For a wallpaper, it's better having colourful, representative, clear pictures, just like a "perfect" picture. I don't think this will look great.

**Comment by NicolasVanBossuyt** [comment]
I agree a more shot of the landscape can be more pleasant to see :)

**Comment by caelwithcats** [comment]
@busybox11 I suppose that's what snow is like

**Comment by busybox11** [comment]
Well, your picture is not really soft, is kinda blurry, has a poor dynamic range and an angle that I would qualify of "not great".

**Pull request closed without merging**
