### PR TITLE
Add --list option to man command

### PR DESCRIPTION
**Pull request by caelwithcats**

### CODE REVIEW

**Comment by NicolasVanBossuyt** [comment]
IMO remove_filename_ext() should be part of the Path object with and be named something like path_filename_without_extension()

**Comment by caelwithcats** [comment]
@NicolasVanBossuyt Actually I want to do a rewrite of that function. One of the problems is the result returned by remove_filename_ext() is heap allocated memory, meaning you have to delete it after it's called. I am not sure how to fix this

**Comment by NicolasVanBossuyt** [comment]
@caelwithcats You can return a libutils/String using this constructor `String(const char *cstring, size_t length)` which managed his memory automagically :^)

**Comment by caelwithcats** [comment]
I think there is some problems with multiple declarations of functions from header files
```c++
libraries/libc/stdio.h:73:7: error: conflicting declaration of C function 'char* strerror(int)'
   73 | char *strerror(int errnum);

```

**Comment by NicolasVanBossuyt** [comment]
What did you include?

**Comment by caelwithcats** [comment]
#include <libutils/String.h>
#include <libjson/Json.h>
```
#include <stdio.h>
#include <libsystem/io/Stream.h>
#include <libsystem/io/Directory.h>
#include <libsystem/utils/BufferBuilder.h>
```

**Comment by NicolasVanBossuyt** [comment]
This is because the function is defined in stdio and shouldn't be. Juste removed line 73 of libc/stdio.h ;)

**Pull request closed without merging**
