### PR TITLE
kernel: make screen black (or another color) before panic

### PR DESCRIPTION
**Pull request by jakiki6**

### CODE REVIEW

**Comment by Supercip971** [comment]
maybe red for showing that it is an error ? or blue

**Comment by caelwithcats** [comment]
Blue, no way - that reminds me of windows too much

**Comment by sleepy-monax** [comment]
tbh I'm not sure if I want my eyes blasted by random colours when debugging at 2am

**Comment by sleepy-monax** [comment]
I think the best color to use is #333333 because it matches the default theme of the system.

**Comment by jakiki6** [comment]
Ok

**Comment by sleepy-monax** [comment]
Can I merge it?

**Pull request merged**
