### PR TITLE
Kernel/Reboot: Reboot on panic

### PR DESCRIPTION
**Pull request by jakiki6**

### CODE REVIEW

**Comment by jakiki6** [comment]
Ok

**Comment by jakiki6** [comment]
When I call it like a C function it gives me ```undefined reference to `__reboot()'```

**Comment by Not-Nik** [comment]
Might be becuase C++ names it functions weirdly and reflects this in extern as well. You could try
```c++
extern "C" void _reboot // Assumes that C converts <name> to _<name>
// or
extern "C" void __reboot // Assumes that C keeps <name>
```

**Comment by NicolasVanBossuyt** [comment]
Neat, maybe add a config flag for that, because I don't want my crash logs buried under the system rebooting. But that's for another PR :)

**Comment by jakiki6** [comment]
Note: It reboots into grub so it doesn't fill your logs unless you press enter.

**Pull request merged**
