### PR TITLE
Window Maximize

### PR DESCRIPTION
**Pull request by Supercip971**
The top right "maximize" button can maximize the window !
at the moment there is a bug: windows are not redrawn when maximized 
so the window has now 2 state : 
maximized and not maximized 
maximized window can't get moved or resized, they can only get de-maximized by pressing the maximize button (on the top right) 
not maximized window are like classic window, they can be resized and moved

### CODE REVIEW

**Comment by caelwithcats** [comment]
@Supercip971 why did you close it

**Comment by NicolasVanBossuyt** [comment]
He just read CONTRIBUTING.md

**Comment by caelwithcats** [comment]
@NicolasVanBossuyt The commit naming convention?

**Comment by NicolasVanBossuyt** [comment]
yes

**Pull request closed without merging**
