### PR TITLE
List class added, currently all methods are defined as public

### PR DESCRIPTION
**Pull request by cristian-programmer**

### CODE REVIEW

**Comment by cristian-programmer** [comment]
To avoid naming issues, call the ListTest class, but then it will be changed to List

**Comment by Supercip971** [comment]
maybe add an operator[] ?

**Comment by cristian-programmer** [comment]
could you give me an example where I should add the operator []

**Comment by sleepy-monax** [comment]
You can avoid the name clash by defining the class in another header file in libutils ;)

**Comment by Supercip971** [comment]
> could you give me an example where I should add the operator []

with operator [] you can just do 
```cpp
my_list_entry_type my_list_entry = my_list[19];
// instead of
my_list_entry_type my_list_entry = my_list.get_entry(19);
```

**Comment by cristian-programmer** [comment]
> You can avoid the name clash by defining the class in another header file in libutils ;)

oh understand thanks :D

**Comment by cristian-programmer** [comment]
> > could you give me an example where I should add the operator []
> 
> with operator [] you can just do
> 
> ```c++
> my_list_entry_type my_list_entry = my_list[19];
> // instead of
> my_list_entry_type my_list_entry = my_list.get_entry(19);
> ```

thanks, I think this could be a type of static list ?, it can be created, but currently List.cpp works as a dynamic list

**Comment by sleepy-monax** [comment]
@cristian-programmer are you still working on this pr ?

**Comment by cristian-programmer** [comment]
> @cristian-programmer are you still working on this pr ?

yes, i'm still working on this
Only I'm a little slow: c

**Pull request closed without merging**
