### PR TITLE
Add a simple script to include contrib packages

### PR DESCRIPTION
**Pull request by jakiki6**

### CODE REVIEW

**Comment by caelwithcats** [comment]
neat :+1:

**Comment by NicolasVanBossuyt** [comment]
Cool 🙂
You can add a SKIFT_CONTRIBROOT to use-it.sh so you don't need to do this ugly ../../../ business ;)

**Comment by jakiki6** [comment]
Ok

**Comment by NicolasVanBossuyt** [comment]
Much cleaner, should I merge it? :)

**Comment by jakiki6** [comment]
It's up to you

**Comment by NicolasVanBossuyt** [comment]
Let's go for it!

**Pull request merged**
